services:
  edge-hailo-face:
    build:
      context: ../..
      dockerfile: edge_hailo/docker/Dockerfile
    image: edge-hailo-face:latest
    restart: unless-stopped
    environment:
      EDGE_HAILO_DB_PATH: /app/edge_hailo/data/device_local.db
      EDGE_HAILO_ACCESS_CAMERA: /dev/video0
      EDGE_HAILO_SURVEILLANCE_CAMERA: /dev/video1
    devices:
      - /dev/hailo0:/dev/hailo0
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    volumes:
      - ../models:/app/edge_hailo/models
      - ../data:/app/edge_hailo/data
    ports:
      - "8080:8080"
