"""Protocols used by the real-time pipeline."""
from typing import Protocol
from .domain import BoundingBox, Embedding, FaceDetection, FramePacket, IdentityMatch
class FaceDetector(Protocol):
    def detect(self, frame: FramePacket) -> list[FaceDetection]: ...
    def set_input_size(self, width: int, height: int) -> None: ...
class FaceTracker(Protocol):
    def initialize(self, frame: FramePacket, box: BoundingBox) -> bool: ...
    def update(self, frame: FramePacket) -> tuple[bool, BoundingBox | None]: ...
    def reset(self) -> None: ...
class FaceRecognizer(Protocol):
    def embed(self, frame: FramePacket, detection: FaceDetection) -> Embedding: ...
    def similarity(self, probe: Embedding, reference: Embedding) -> float: ...
class FaceQualityEvaluator(Protocol):
    def evaluate(self, frame: FramePacket, detection: FaceDetection): ...
class CameraSource(Protocol):
    def start(self) -> None: ...
    def read(self) -> FramePacket | None: ...
    def stop(self) -> None: ...
class IdentityRepository(Protocol):
    def find_match(self, embedding: Embedding) -> IdentityMatch | None: ...
class AccessController(Protocol):
    def unlock(self, identity_id: str, duration_seconds: float) -> bool: ...
class DatabaseSyncService(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def status(self) -> str: ...