"""Create persistent local secrets for production-like laptop testing.

This is a local bootstrap substitute for a real deployment secret manager. It
never writes secrets into the repository and never rotates an existing store
unless explicitly requested.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

from cryptography.fernet import Fernet


def default_path() -> Path:
    return Path.home() / ".smart-campus-cloud" / "production-secrets.env"


def main() -> int:
    parser = argparse.ArgumentParser(description="Bootstrap persistent local production secrets")
    parser.add_argument("--path", type=Path, default=default_path())
    parser.add_argument("--rotate", action="store_true", help="Replace an existing store; this invalidates existing sessions/device credentials")
    args = parser.parse_args()
    path = args.path.expanduser().resolve()

    if path.exists() and not args.rotate:
        print(f"Secret store already exists: {path}")
        print("No secrets were changed.")
        return 0

    path.parent.mkdir(parents=True, exist_ok=True)
    jwt_secret = os.urandom(48).hex()
    device_credential_key = Fernet.generate_key().decode()
    temporary_path = path.with_suffix(path.suffix + ".tmp")
    temporary_path.write_text(
        "# Generated by bootstrap_local_production_secrets.py; keep outside Git.\n"
        f"JWT_SECRET={jwt_secret}\n"
        f"DEVICE_CREDENTIAL_KEY={device_credential_key}\n",
        encoding="utf-8",
    )
    os.replace(temporary_path, path)
    try:
        path.chmod(0o600)
    except OSError:
        pass
    print(f"Created persistent production secret store: {path}")
    print("Set APP_ENV=production and restart the cloud backend.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
